# Generated by Django 4.2.15 on 2024-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="通用名")),
                (
                    "sales_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="销售金额"
                    ),
                ),
                (
                    "sales_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="销售数量"
                    ),
                ),
            ],
        ),
    ]
