# Generated by Django 4.2.15 on 2024-08-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_attributekey_alter_storeattribute_attribute_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeattribute",
            name="attribute_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="stores.attributekey"
            ),
        ),
    ]
