# Generated by Django 4.2.15 on 2024-08-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0003_alter_storeattribute_attribute_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeattribute",
            name="attribute_type",
        ),
        migrations.AddField(
            model_name="attributekey",
            name="attribute_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("datetime", "Datetime"),
                    ("boolean", "Boolean"),
                    ("json", "JSON"),
                    ("file", "File"),
                    ("image", "Image"),
                ],
                default="text",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="storeattribute",
            name="attribute_file",
            field=models.FileField(blank=True, null=True, upload_to="store_files/"),
        ),
        migrations.AddField(
            model_name="storeattribute",
            name="attribute_image",
            field=models.ImageField(blank=True, null=True, upload_to="store_images/"),
        ),
        migrations.AlterField(
            model_name="storeattribute",
            name="attribute_value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
