# Generated by Django 4.2.15 on 2024-08-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0004_remove_storeattribute_attribute_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributekey",
            name="key_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="attributekey",
            constraint=models.UniqueConstraint(
                fields=("key_name", "attribute_type"), name="unique_key_name_type"
            ),
        ),
    ]
